server:
  port: 8000

spring:
  application:
    name: Monitoring Service
  cloud:
    circuit:
      breaker:
        enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true
